name: Golang Build

on: [push, workflow_dispatch, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Building
        run: go build -v ./...
      - name: Running golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Testing
        run: go test -v ./...
